---
title: "Election Predction Linear Model"
author: "Enzo Moraes Mescall"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
sentiment_data = read.csv("baseline_data.csv")
state_data = read.csv("Popular vote backend - Sheet1.csv") %>%
  dplyr::select(state, dem_this_margin)
```

```{r}
swing_states = c("Arizona", "Florida", "Georgia", "Iowa", "Maine", "Michigan",
                 "Minnesota", "Nebraska", "Nevada", "New Hampshire", "North Carolina",
                 "Ohio", "Pennsylvania", "Texas", "Wisconsin", "Florida", "Michigan", "Ohio", "Pennsylvania")
```


```{r}
# creating dataset and predictor
baseline = sentiment_data %>%
  inner_join(state_data) %>%
  mutate("dem_this_margin" = as.numeric(as.numeric(sub("%","",dem_this_margin))/100)) %>%
  mutate(biden_pos_pct = biden.positive/(biden.positive+biden.neutral+biden.negative))

test = subset(baseline, state %in% swing_states)
train = subset(baseline, !(state %in% swing_states))
```
```{r}
model_df = train %>%
  dplyr::select(-state)
model = lm(dem_this_margin~.*biden.positive + .*trump.positive, data = model_df)

library(MASS)

step.model <- stepAIC(model, direction = "forward", 
                      trace = FALSE, k = log(50))
```

```{r}


test_model_df = test  %>%
  modelr::add_predictions(model) %>%
  mutate(accurate = (dem_this_margin*pred > 0))

sum(test_model_df$accurate)/nrow(test_model_df)

pred_model_df = baseline  %>%
  modelr::add_predictions(model) %>%
  mutate(accurate = (dem_this_margin*pred > 0))

sum(pred_model_df$accurate)/nrow(pred_model_df)
```

```{r}
library(rvest) #Web-Scraping
library(tidyverse) #Data Cleaning and Plotting
library(httr) #Used to Download Excel File from Web
library(readxl) #Read in Excel Files

electoral_votes <- read_html('https://en.wikipedia.org/wiki/United_States_Electoral_College') %>% 
  html_nodes("table") %>% 
  .[[5]] %>% 
  html_table(fill = T) %>% 
  dplyr::select(2, 4, 36) %>% 
  filter(!Electionyear %in% c('Total', 'Electionyear', "State")) %>% 
  rename(state = 1, electoral_votes_1792 = 2, electoral_votes_2020 = 3) %>% 
  mutate(across(starts_with('electoral_votes'), parse_number))


electoral_model = pred_model_df %>% inner_join(electoral_votes) %>%
  filter(pred > 0)

sum(electoral_model$electoral_votes_2020)
```







